version: 2
jobs:
  build:
    docker:
      - image: circleci/node:erbium

    working_directory: ~/repo

    steps:
      - checkout

      - run: echo $ENV_FILE | base64 --decode > .env

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
            - v1-dependencies-

      - run: npm install
      - run: cd functions && npm install
      - run: npm install -D firebase-tools

      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}

      - run: npm run generate

      - run: ./node_modules/.bin/firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
